---
platform: trusty
db_prefix: db
lb_prefix: lb
domain_suffix: ".v" # fqdn necessary for `erl -name` to work
install_dir: /root
bin_dir: /opt/cloudant/bin
config_dir: /opt/cloudant/.config
cast_config_dir: /opt/cloudant/cast/etc
rebal_dir: /opt/cloudantrebal
admin_password: pass
