---
# installation tasks common to all node types

- hosts: all
  sudo: true
  gather_facts: false
  vars:
    archive: "{{ lookup('pipe', 'ls -1 cloudant-*.tar.gz | tail -n1') }}"
    repo_dir: "{{ install_dir }}/cloudant/repo"
  tasks:
    - copy: src={{ archive }} dest={{ install_dir }}/
    - unarchive: src={{ install_dir }}/{{ archive }} dest={{ install_dir }}/ copy=no
    - command: ./install.bin -i silent -f production.properties
      args:
        chdir: '{{ install_dir }}/cloudant-installer'
        creates: '{{ install_dir }}/cloudant/repo'
    - apt: update_cache=yes
    - apt: name=python-pip
    - apt: name=cloudant-cast state=latest force=yes # force necessary for re-install?
    - lineinfile: dest=/home/vagrant/.bashrc line="alias r='sudo su - root'"
