---
# installation tasks common to all node types

- hosts: all
  sudo: true
  gather_facts: false
  vars:
    archive_cmd: 'ls -1 cloudant-*-{{platform}}-*.tar.gz | tail -n1'
    archive: '{{ lookup("pipe", archive_cmd) }}'
    repo_dir: '{{ install_dir }}/cloudant/repo'
  tasks:
    - debug: var=archive
    - copy: src={{ archive }} dest={{ install_dir }}/
    - unarchive: src={{ install_dir }}/{{ archive }} dest={{ install_dir }}/ copy=no
    - command: ./install.bin -i silent -f production.properties
      args:
        chdir: '{{ install_dir }}/cloudant-installer'
        creates: '{{ install_dir }}/cloudant/repo'
    - lineinfile: dest=/home/vagrant/.bashrc line="alias r='sudo su - root'"
    - file: path={{ config_dir }} state=directory owner=cloudant group=cloudant

    # FIXME: these should be installed automatically by previous step BugzID: 62253
    - apt: name=python-pip
    - apt: name=cloudant-cast state=latest force=yes # force necessary for re-install?
