---
- hosts: all
  become: yes
  become_user: root
  gather_facts: false
  tasks:
    - shell: cast system install -lb
      args:
        creates: /etc/haproxy # better way?
    - copy: src=files/gen_lbnode_yaml.py dest={{ cast_config_dir }}/
    - shell: DB_PREFIX={{ db_prefix }} python gen_lbnode_yaml.py < /etc/hosts > lbnode.yaml
      args:
        chdir: '{{ cast_config_dir }}'
    - command: cast node config {{ cast_config_dir }}/lbnode.yaml
