---
- hosts: all
  become: yes
  become_user: root
  gather_facts: false
  vars:
    erl_call: '{{ bin_dir }}/erl_call_cloudant'
  tasks:
    - command: cast system install -db creates=/opt/cloudant/lib
    - template: src=files/dbnode.yaml dest={{ config_dir }}/
    - command: cast node config {{ config_dir }}/dbnode.yaml
    - copy: src=files/block_until_db_up.sh dest={{ config_dir }}/ mode=0755
    - shell: '{{ config_dir }}/block_until_db_up.sh'
    - copy: src=files/cluster.sh dest={{ config_dir }}/ mode=0755
    - shell: DB_PREFIX={{ db_prefix }} {{ config_dir }}/cluster.sh
    - lineinfile: line="alias tl='tail -f /var/log/cloudant/cloudant.log'"
                  dest=/root/.bashrc
    - command: '{{ erl_call }} -a "config set [\"log\", \"level\", \"notice\"]"'
    - copy: src=files/id_rsa.pub dest={{ rebal_dir }}/.ssh/authorized_keys
        owner=cloudantrebal group=cloudant
    - copy: src={{ item }} dest={{ rebal_dir }}/.ssh/ mode=0600
        owner=cloudantrebal group=cloudant
      with_fileglob:
        - ./files/id_rsa*
