---
- hosts: all
  sudo: true
  gather_facts: false
  vars:
    append_bin_path: 'PATH=$PATH:{{ bin_dir }}'
    erl_call: '{{ bin_dir }}/erl_call_cloudant'
  tasks:
    - command: cast system install -db
      args:
        creates: /opt/cloudant/lib # better choice?
    - template: src=files/dbnode.yaml dest={{ config_dir }}/
    - command: cast node config {{ config_dir }}/dbnode.yaml
    - copy: src=files/block_until_db_up.sh dest={{ config_dir }}/ mode=0755
    - shell: '{{ config_dir }}/block_until_db_up.sh'
    - copy: src=files/cluster.sh dest={{ config_dir }}/ mode=0755
    - shell: '{{ config_dir }}/cluster.sh'
    - lineinfile: dest=/root/.bashrc line={{ append_bin_path }}
    - lineinfile: dest=/root/.bashrc line="alias tl='tail -f /var/log/cloudant/cloudant-svlogd/current'"
    - lineinfile: dest=/home/vagrant/.bashrc line={{ append_bin_path }}
    - command: '{{ erl_call }} -a "config set [\"log\", \"level\", \"info\"]"'
