---
# installation tasks common to all node types

- hosts: all
  sudo: true
  gather_facts: false
  vars:
    archive: "{{ lookup('pipe', 'ls -1 cloudant-*.tar.gz | tail -n1') }}"
    repo_dir: "{{ install_dir }}/cloudant/repo"
    vagrant_host_name: ldap.local
  tasks:
    - copy: src={{ archive }} dest={{ install_dir }}/
    - unarchive: src={{ install_dir }}/{{ archive }} dest={{ install_dir }}/ copy=no
    - command: ./install.bin -i silent -f production.properties
      args:
        chdir: '{{ install_dir }}/cloudant-installer'
        creates: '{{ install_dir }}/cloudant/repo'
    - apt: name=python-pip
    - shell: dpkg -i {{ repo_dir }}/pool/main/c/cloudant-cast/cloudant-cast_*.deb
    - command: cast system addrepo {{ repo_dir }}
    - shell: netstat -rn | grep "^0.0.0.0 " | cut -d " " -f10
      register: netstat_cmd
    - set_fact: host_ipaddr={{ netstat_cmd.stdout }}
    - lineinfile: dest=/etc/hosts line='{{ host_ipaddr }} {{ vagrant_host_name }}'