---
# uninstall any existing installer, packages and configuration

- hosts: all
  sudo: true
  gather_facts: false
  tasks:
    - name: clean up any existing expanded archive
      file: path={{ install_dir }}/cloudant-installer state=absent
    - name: clean up any installed repos
      command: '{{ install_dir }}/cloudant/uninstall/uninstall.bin'
      args:
        removes: '{{ install_dir }}/cloudant'
    - apt: name=cloudant-cast state=absent purge=yes
    - apt: name=cloudant-base state=absent purge=yes
